# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
jobs:
  test-php73:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip sockets
      
      - run:
          name: "Create Environment file"
          command: |
            mv .env.example .env

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v73-dependencies-{{ checksum "composer.json" }}
            # Fallback to using the latest cache if no exact match is found.
            - v73-dependencies-

      - run: composer update --prefer-lowest --prefer-stable --no-interaction

      - save_cache:
          key: v73-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      # - run: ./vendor/bin/phpcs .
      - run: ./vendor/bin/phpunit

  test-php74:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip sockets
      
      - run:
          name: "Create Environment file"
          command: |
            mv .env.example .env

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v74-dependencies-{{ checksum "composer.json" }}
            # Fallback to using the latest cache if no exact match is found.
            - v74-dependencies-

      - run: composer update --no-interaction

      - save_cache:
          key: v74-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
           
      - run:
          name: "Generate App key"
          command: php artisan key:generate
         
      # - run: ./vendor/bin/phpcs .
      - run: ./vendor/bin/phpunit

  test-php80:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install zip sockets
      
      - run:
          name: "Create Environment file"
          command: |
            mv .env.example .env

      # Download and cache dependencies.
      - restore_cache:
          keys:
            - v80-dependencies-{{ checksum "composer.json" }}
            # Fallback to using the latest cache if no exact match is found.
            - v80-dependencies-

      - run: composer update --no-interaction

      - save_cache:
          key: v80-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate
          
      # - run: ./vendor/bin/phpcs .
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  test-php-versions:
    jobs:
      - test-php73
      - test-php74
      - test-php80
